###
# Configuration for Vagrant
###
name: wcjkl
production:
  # This is used to automatically fetch data from a staging/production environment
  domain: ccthwpd.fi.seravo.com
  ssh_port: 10695
  url: https://ccthwpd.fi.seravo.com/
development:
  # Domains are automatically mapped to Vagrant with /etc/hosts modifications
  domains:
    - wcjkl.local
  # If you want to use zeroconf (.local domains) in your network you can use this.
  #avahi: true
